# Generated by Django 4.0 on 2022-01-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeasonMall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
    ]
