# Generated by Django 4.0 on 2022-01-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeasonMall', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='SeasonMall/photos'),
        ),
    ]
