# Generated by Django 4.0 on 2022-01-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeasonMall', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/media/uploads/SM.png', null=True, upload_to='uploads/'),
        ),
    ]
